agents:
  coordinator:
    prompt: coordinator
    tools:
      - test_tool
    section: null
    output_schema: null
    approach: null
    dynamic: false
    batch_enabled: false

  preface_agent:
    prompt: preface_agent
    tools:
      - test_tool
    section: preface
    output_schema: 01-preface.json
    approach: null
    dynamic: false
    batch_enabled: false

  getting_started_agent:
    prompt: getting_started_agent
    tools:
      - test_tool
    section: getting_started
    output_schema: 02-getting-started.json
    approach: null
    dynamic: false
    batch_enabled: false

  features_agent:
    prompt: features_agent
    tools:
      - test_tool
    section: features
    output_schema: 03-01-list-of-features.json
    approach: null
    dynamic: false
    batch_enabled: false

  entity_agent:
    prompt: entity_agent
    tools:
      - test_tool
    section: entity
    output_schema: 05-entity.json
    approach: null
    dynamic: false
    batch_enabled: false
